
# ===============================
# CONFIGURACION GENERAL DEL SERVIDOR
# ===============================
server:
  port: 8081
  servlet:
    context-path: /api  # opcional, para definir prefijo en las rutas

# ===============================
# CONFIGURACION DE LA BASE DE DATOS ORACLE
# ===============================
spring:
  datasource:
    url: jdbc:oracle:thin:@a8l4bsvsef6piv46_medium?TNS_ADMIN=./wallet_ORACLE
    username: ${ORACLE_USER}
    password: ${ORACLE_PASS}
    driver-class-name: oracle.jdbc.OracleDriver

jpa:
  hibernate:
    ddl-auto: none  # create, update, validate o none
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.OracleDialect

# Control de perfiles (opcional)
#profiles:
#  active: dev


# ===============================
# CONFIGURACION DE LOGGING
# ===============================
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/app.log  # Guarda logs en un archivo local

# ===============================
# CONFIGURACION PERSONALIZADA
# ===============================
app:
  nombre: "Servicio de Gestion de Laboratorios"
  version: "1.0.0"
  descripcion: "API REST con Spring Boot, Oracle y JWT"